supported_paper_game_versions: &supported_paper_game_versions
  - "1.20.6"
  - "1.21"
  - "1.21.1"
  - "1.21.2"
  - "1.21.3"
  - "1.21.4"
  - "1.21.5"
  - "1.21.6"
  - "1.21.7"
  - "1.21.8"
  - "1.21.9"
  - "1.21.10"
  - "1.21.11"
  - "26.1"
  - "26.1.1"
  - "26.1.2"

supported_bukkit_game_versions: &supported_bukkit_game_versions
  - "1.16"
  - "1.16.1"
  - "1.16.2"
  - "1.16.3"
  - "1.16.4"
  - "1.16.5"
  - "1.17"
  - "1.17.1"
  - "1.18"
  - "1.18.1"
  - "1.18.2"
  - "1.19"
  - "1.19.1"
  - "1.19.2"
  - "1.19.3"
  - "1.19.4"
  - "1.20"
  - "1.20.1"
  - "1.20.2"
  - "1.20.3"
  - "1.20.4"
  - "1.20.5"
  - "1.20.6"
  - "1.21"
  - "1.21.1"
  - "1.21.2"
  - "1.21.3"
  - "1.21.4"
  - "1.21.5"
  - "1.21.6"
  - "1.21.7"
  - "1.21.8"
  - "1.21.9"
  - "1.21.10"
  - "1.21.11"
  - "26.1"
  - "26.1.1"
  - "26.1.2"

supported_velocity_game_versions: &supported_velocity_game_versions
  - "1.16"
  - "1.16.1"
  - "1.16.2"
  - "1.16.3"
  - "1.16.4"
  - "1.16.5"
  - "1.17"
  - "1.17.1"
  - "1.18"
  - "1.18.1"
  - "1.18.2"
  - "1.19"
  - "1.19.1"
  - "1.19.2"
  - "1.19.3"
  - "1.19.4"
  - "1.20"
  - "1.20.1"
  - "1.20.2"
  - "1.20.3"
  - "1.20.4"
  - "1.20.5"
  - "1.20.6"
  - "1.21"
  - "1.21.1"
  - "1.21.2"
  - "1.21.3"
  - "1.21.4"
  - "1.21.5"
  - "1.21.6"
  - "1.21.7"
  - "1.21.8"
  - "1.21.9"
  - "1.21.10"
  - "1.21.11"
  - "26.1"
  - "26.1.1"
  - "26.1.2"

release:
  classification:
    rules:
      - phase: release
        patterns:
          - '^v?\d+\.\d+\.\d+$'
      - phase: beta
        patterns:
          - '^v?\d+\.\d+\.\d+-rc\d+$'
      - phase: alpha
        patterns:
          - '^dev-[0-9a-f]+$'
    default_phase: release

artifacts:
  socialismus-paper:
    file: Socialismus-PAPER-{version}.jar
    platform: paper
    loaders:
      - folia
      - paper
      - purpur
    game_versions: *supported_paper_game_versions

  socialismus-bukkit:
    file: Socialismus-BUKKIT-{version}.jar
    platform: bukkit
    loaders:
      - bukkit
      - paper
      - purpur
      - spigot
    game_versions: *supported_bukkit_game_versions

  socialismus-velocity:
    file: Socialismus-VELOCITY-{version}.jar
    platform: velocity
    loaders:
      - velocity
    game_versions: *supported_velocity_game_versions

publications:
  socialismus-paper-modrinth:
    provider:
      id: modrinth
      project_id: aeIrNw73
      release_type_map:
        release: release
        beta: beta
        alpha: alpha
    artifact: socialismus-paper

  socialismus-bukkit-modrinth:
    provider:
      id: modrinth
      project_id: aeIrNw73
      release_type_map:
        release: release
        beta: beta
        alpha: alpha
    artifact: socialismus-bukkit

  socialismus-velocity-modrinth:
    provider:
      id: modrinth
      project_id: aeIrNw73
      release_type_map:
        release: release
        beta: beta
        alpha: alpha
    artifact: socialismus-velocity
