rootProject.name = "Socialismus"

include("socialismus-integration:integration-papiproxybridge")
include("socialismus-integration:integration-placeholderapi")
include("socialismus-integration:integration-packetevents")
include("socialismus-integration:integration-valiobungee")
include("socialismus-integration:integration-bstats")
include("socialismus-platform:platform-velocity")
include("socialismus-platform:platform-bukkit")
include("socialismus-platform:platform-paper")
include("socialismus-adapter-command")
include("socialismus-adapter-config")
include("socialismus-adapter-module")
include("socialismus-common-api")
include("socialismus-common")
include("socialismus-shared")
