[versions]

# plugins
shadow = "9.3.0"
buildconfig = "5.7.1"

# compile time processing
lombok = "1.18.42"

# general
guice = "7.0.0"
annotations = "26.0.1"
attache = "dev-6254018"
configura = "dev-a76adc6"
keystone = "dev-697f401"
commandant = "dev-5f99bce"

# testing
junit = "6.0.0"
mockito = "5.20.0"

# resouces
ormlite = "6.1"
jedis = "7.0.0"

# platform api versions
velocity = "3.4.0-SNAPSHOT"
spigot = "1.21.7-R0.1-SNAPSHOT"
paper = "1.21.7-R0.1-SNAPSHOT"

# platform integrations
placeholderAPI = "2.11.6"
papiProxyBridge = "1.8.4"
bStats = "3.1.0"

# adventure
adventure = "4.24.0"
adventure-minimessage = "4.23.0"
adventure-legacy = "4.24.0"
adventure-plain = "4.23.0"
adventure-gson = "4.23.0"
adventure-platform-bukkit = "4.4.1"

# cloud
cloud-core = "2.0.0"
cloud-paper = "2.0.0-beta.13"
cloud-velocity = "2.0.0-beta.13"
cloud-cooldown = "1.0.0-rc.1"
cloud-minecraft-extras = "2.0.0-beta.13"

# brigadier
brigadier = "1.0.18"

[libraries]

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
configura = { group = "me.whereareiam", name = "configura", version.ref = "configura" }
keystone = { group = "me.whereareiam", name = "keystone", version.ref = "keystone" }
commandant = { group = "me.whereareiam", name = "commandant", version.ref = "commandant" }

# attache
attache-bukkit = { group = "me.whereareiam", name = "attache-bukkit", version.ref = "attache" }
attache-paper = { group = "me.whereareiam", name = "attache-paper", version.ref = "attache" }
attache-velocity = { group = "me.whereareiam", name = "attache-velocity", version.ref = "attache" }
attache-common = { group = "me.whereareiam", name = "attache-common", version.ref = "attache" }

# resources
ormlite = { group = "com.j256.ormlite", name = "ormlite-core", version.ref = "ormlite" }

# platform api
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# platform integrations
placeholderAPI = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderAPI" }
papiProxyBridge = { group = "net.william278", name = "papiproxybridge", version.ref = "papiProxyBridge" }
bStats = { group = "org.bstats", name = "bstats-base", version.ref = "bStats" }
bStats-velocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bStats" }
bStats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bStats" }

# adventure
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-minimessage" }
adventure-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure-legacy" }
adventure-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure-plain" }
adventure-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure-gson" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform-bukkit" }

# cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud-core" }
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud-core" }
cloud-cooldowns = { group = "org.incendo", name = "cloud-processors-cooldown", version.ref = "cloud-cooldown" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-paper" }
cloud-velocity = { group = "org.incendo", name = "cloud-velocity", version.ref = "cloud-velocity" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft-extras" }

# brigadier
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[bundles]

adventure = ["adventure", "adventure-minimessage", "adventure-legacy", "adventure-plain", "adventure-gson"]
bukkit = ["spigot", "adventure-platform-bukkit"]
paper = ["paper"]
velocity = ["velocity"]
cloud = ["cloud-core", "cloud-annotations", "cloud-cooldowns", "cloud-minecraft-extras"]
testing = ["junit-jupiter", "mockito-core", "mockito-junit"]

bStats = ["bStats", "bStats-bukkit", "bStats-velocity"]
bStats-bukkit = ["bStats", "bStats-bukkit"]
bStats-velocity = ["bStats", "bStats-velocity"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }