name: Development build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.details.outputs.name }}
      version: ${{ steps.details.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract project details
        id: details
        run: |
          echo "name=$(grep 'rootProject.name' settings.gradle.kts | awk -F "=" '{print $2}' | tr -d ' \"\n')" >> $GITHUB_OUTPUT
          branch_name="${GITHUB_REF_NAME//\//-}"
          echo "version=${branch_name}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: always() && needs.prepare.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build project
        uses: ./.github/actions/gradle-build
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          VERSION: ${{ needs.prepare.outputs.version }}
          PUBLISH_REALM: development
        with:
          gradle-command: ./gradlew --no-daemon test jars publish -Dsocialismus.liveApiTests=true
          ignore-test-failures: 'true'

      - name: Create output directory
        run: mkdir output

      - name: Move jars
        run: cp build/jars/*.jar output/

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build artifacts
          path: output/
