name: Release build

on:
  release:
    types: [ created ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.details.outputs.name }}
      version: ${{ steps.details.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project details
        id: details
        run: |
          echo "name=$(grep 'rootProject.name' settings.gradle.kts | awk -F "=" '{print $2}' | tr -d ' \"\n')" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true

      - name: Build project
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
        run: ./gradlew build shadowJar

      - name: Create output directory
        run: mkdir output

      - name: Move API
        run: mv socialismus-common-api/build/libs/socialismus-common-api-${{ needs.prepare.outputs.version }}.jar output/${{ needs.prepare.outputs.name }}-API-${{ needs.prepare.outputs.version }}.jar

      - name: Move platform jars
        run: |
          mv build/libs/${{ needs.prepare.outputs.name }}-${{ needs.prepare.outputs.version }}-PAPER.jar output/${{ needs.prepare.outputs.name }}-PAPER-${{ needs.prepare.outputs.version }}.jar
          mv build/libs/${{ needs.prepare.outputs.name }}-${{ needs.prepare.outputs.version }}-BUKKIT.jar output/${{ needs.prepare.outputs.name }}-BUKKIT-${{ needs.prepare.outputs.version }}.jar
          mv build/libs/${{ needs.prepare.outputs.name }}-${{ needs.prepare.outputs.version }}-VELOCITY.jar output/${{ needs.prepare.outputs.name }}-VELOCITY-${{ needs.prepare.outputs.version }}.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/${{ needs.prepare.outputs.name }}-API-${{ needs.prepare.outputs.version }}.jar
            output/${{ needs.prepare.outputs.name }}-PAPER-${{ needs.prepare.outputs.version }}.jar
            output/${{ needs.prepare.outputs.name }}-BUKKIT-${{ needs.prepare.outputs.version }}.jar
            output/${{ needs.prepare.outputs.name }}-VELOCITY-${{ needs.prepare.outputs.version }}.jar

  publish:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true

      - name: Publish API to Maven repository
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          VERSION: ${{ needs.prepare.outputs.version }}
          PUBLISH_REALM: release
        run: ./gradlew --no-daemon publish