name: Release Drafter

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Update release draft
        id: drafter
        uses: release-drafter/release-drafter@v7
        with:
          commitish: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Regroup draft release
        uses: whereareiam/blockops/actions/release/regroup-draft-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-id: ${{ steps.drafter.outputs.id }}
          release-body: ${{ steps.drafter.outputs.body }}
